-- +migrate Up
-- Preserve existing monitoring data by widening append-only event ids in place.
-- Application resource ids were already TEXT, so the UUID rollout only needs these
-- write-heavy tables to accept the new UUID string ids generated by the app.
ALTER TABLE metric_points
  ALTER COLUMN id DROP DEFAULT,
  ALTER COLUMN id TYPE TEXT USING id::TEXT;

ALTER TABLE log_lines
  ALTER COLUMN id DROP DEFAULT,
  ALTER COLUMN id TYPE TEXT USING id::TEXT;

ALTER TABLE event_logs
  ALTER COLUMN id DROP DEFAULT,
  ALTER COLUMN id TYPE TEXT USING id::TEXT;

-- +migrate Down
-- Recreate numeric surrogate ids without dropping any rows.
ALTER TABLE metric_points
  RENAME COLUMN id TO legacy_id;
ALTER TABLE metric_points
  ADD COLUMN id BIGSERIAL;
ALTER TABLE metric_points
  DROP CONSTRAINT metric_points_pkey;
ALTER TABLE metric_points
  ADD PRIMARY KEY (id);
ALTER TABLE metric_points
  DROP COLUMN legacy_id;

ALTER TABLE log_lines
  RENAME COLUMN id TO legacy_id;
ALTER TABLE log_lines
  ADD COLUMN id BIGSERIAL;
ALTER TABLE log_lines
  DROP CONSTRAINT log_lines_pkey;
ALTER TABLE log_lines
  ADD PRIMARY KEY (id);
ALTER TABLE log_lines
  DROP COLUMN legacy_id;

ALTER TABLE event_logs
  RENAME COLUMN id TO legacy_id;
ALTER TABLE event_logs
  ADD COLUMN id BIGSERIAL;
ALTER TABLE event_logs
  DROP CONSTRAINT event_logs_pkey;
ALTER TABLE event_logs
  ADD PRIMARY KEY (id);
ALTER TABLE event_logs
  DROP COLUMN legacy_id;
